# [Fundamental Python Data Science Libraries: A Cheatsheet (Part 1/4)](https://hackernoon.com/fundamental-python-data-science-libraries-a-cheatsheet-part-1-4-58884e95c2bd)

by [Lauren Glass](https://www.linkedin.com/in/laurenjglass/), [Hackernoon](https://hackernoon.com/), Dec. 20, 2017

## NumPy

Just as it is written on NumPy’s website, this library is fundamental for scientific computing in Python. It includes powerful manipulation and mathematical functionality at super fast speeds.

This library is all about the multidimensional array. It is similar in appearance to a list & indexes like a list, but carries a much more powerful set of tools.

In [35]:
import numpy as np

In [2]:
# Create array from a list or tuple

# 1 dimensional array (you can pick more)
future_array1 = [1,2,3,4,5]
array1 = np.array(future_array1)

In [4]:
array1

array([1, 2, 3, 4, 5])

In [36]:
# Create array with placeholder content

# there are other placeholder options, see jupyter notebook below
placeholder_zero = np.zeros((3,4), dtype=np.int) # default np.float


In [6]:
placeholder_zero

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [37]:
# Create array with a sequence

# sequence based on steps (start, end, step_value)
sequence_array1 = np.arange(10, 30, 4)
# evenly spaced sequence based on number specified
# (start, end, number_of_elements)
sequence_array2 = np.linspace(10, 30, 4)

In [12]:
sequence_array1

array([10, 14, 18, 22, 26])

In [13]:
sequence_array2

array([ 10.        ,  16.66666667,  23.33333333,  30.        ])

In [34]:
# Upload data: csv file contain comma separated values
#data = np.genfromtxt("your_file_here.csv", delimiter=",")

In [16]:
# Makes Math Easy

a1 = np.array([1,2,3,4])
a2 = np.ones((1,4), dtype=np.int)
a3 = np.zeros((1,4), dtype=np.int)
# Addition/Subtraction
A = a1 + a2 - a3
# Multiplication/Division
B = a2 * a3 / a2

In [17]:
A

array([[2, 3, 4, 5]])

In [18]:
B

array([[ 0.,  0.,  0.,  0.]])

In [39]:
# Attributes & Methods

# Summary Statistics

array1.mean()

3.0

In [24]:
array1.max()

5

In [25]:
array1.sum()

15

In [40]:
# Reshape arrays

A = np.array([1,2,3,4,5,6,7,8,9,100])
B = A.reshape((2,5)) # takes a tuple of dimensions
C = B.T # transpose

In [27]:
B

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9, 100]])

In [28]:
C

array([[  1,   6],
       [  2,   7],
       [  3,   8],
       [  4,   9],
       [  5, 100]])

In [41]:
# More Math

D = A.reshape((1,10))

In [30]:
D

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9, 100]])

## Application :: cumulative sum

In [31]:
import numpy as np

# deposited $100,000 and then started buying and selling
trades = [100000, -10000, 10500, -100000, 175000]

In [32]:
# convert my trades to a numpy array
trades_array = np.array(trades)

In [33]:
trades_array.cumsum()

array([100000,  90000, 100500,    500, 175500])